#!/bin/sh

set -eu

usage() {
    regex="^(store|(move )?(primary|secondary) [1-4])$"
    if egrep -v "$regex" <<< "$@" > /dev/null; then
        echo "Usage: ./select-workspace $regex"
        exit
    fi
}

hc() {
    herbstclient "$@"
}

name() {
    hc get_attr tags.focus.name
}

name_primary() {
    name | egrep -o '^.'
}

name_secondary() {
    name | egrep -o '.$'
}

secondary() {
    primary=$1
    output=$(sed -n "/^$primary/ { s/^[0-9]* //; p }" < $storage)
    if [ -z "$output" ]; then
        echo 1
    else
        echo $output
    fi
}

save() {
    (egrep -v "^$1" $storage; echo "$1 $2") > ${storage}.tmp || true
    mv ${storage}.tmp $storage
}

usage "$@"

if [ "$1" == 'move' ]; then
    move=1
    shift
else
    move=0
fi

field=$1
! [ -z "${2-}" ] && value=$2 && shift
shift

storage=/tmp/.workspaces
[ -e $storage ] || touch $storage

if [ "$field" == 'store' ]; then
    save $(name_primary) $(name_secondary)

elif [ "$field" == 'primary' ]; then
    printf "%s%s" $value $(secondary $value)

elif [ "$field" == 'secondary' ]; then
    p=$(name_primary)
    printf "%s%s" $p $value

    if [ "$move" == "0" ]; then
        save $p $value
    fi
fi
